---
name: Tee
version: 0.13_51
author:
  - 'David Golden <dagolden@cpan.org>'
abstract: Pure Perl emulation of GNU tee
license: apache
resources:
  license: http://apache.org/licenses/LICENSE-2.0
requires:
  Exporter: 0
  File::Basename: 0
  Getopt::Long: 2.2
  IO::File: 0
  Probe::Perl: 0.01
build_requires:
  File::Spec: 3.27
  File::Temp: 0.2
  IO::CaptureOutput: 1.09
  Test::More: 0.47
provides:
  Tee:
    file: lib/Tee.pm
    version: 0.13_51
  Tee::App:
    file: lib/Tee/App.pm
    version: 0.13_51
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  directory:
    - examples
    - inc
    - t
